name: build-ubuntu
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: # Enables manually
# on:
#  push:
#    branches:
#      - master
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        version: [6.8.3, 6.9.1]
        arch: gcc_64
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: install qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: ${{ matrix.version }}
          target: 'desktop'
          arch: ${{ matrix.arch }}
          dir: ${{ github.workspace }}
          modules: 'qtcharts qtserialbus qtserialport qtwebsockets'
      - name: install-dependencies
        run: |
          sudo apt-get install -y libxcb-xinerama0 libxcb-cursor-dev  libudev-dev libusb-dev libusb-1.0-0-dev
      - name: build for linux
        run: |
          git fetch --tags
          cmake --version
          mkdir build
          cd build
          cmake -DCMAKE_PREFIX_PATH='${{ github.workspace }}/Qt/${{ matrix.version }}/${{ matrix.arch }}' -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ../
          cmake --build . --target xTools
          cmake --build . --target xTools_linux
